[package]
name = "mtk"
version = "0.0.0"
edition = "2024"

[lib]
name = "mtk"
path = "src/lib.rs"


[dependencies]
chrono = "0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tempfile = "3.20.0"
